version: '3'
services:
 jenkins:
   container_name: jenkins
   image: jenkins:latest
   build:
     context: .
     network: host
   ports:
     - "8099:8080"
   volumes:
     - "$PWD/jenkins_home:/var/jenkins_home"
     - "/var/run/docker.sock:/var/run/docker.sock" 
